spring.application.name=security
server.port=1050
spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.security.user.name=admin
#spring.security.user.password=admin123